// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordApplicationCommandOptionChoiceBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Applications;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordApplicationCommandOptionChoiceBuilder
{
	private string _name = default!;
	private object _value = default!;

	public DiscordApplicationCommandOptionChoiceBuilder WithName(string name)
	{
		_name = name;
		return this;
	}

	public DiscordApplicationCommandOptionChoiceBuilder WithValue(object value)
	{
		_value = value;
		return this;
	}

	public DiscordApplicationCommandOptionChoice Build() =>
		new()
		{
			Name = _name,
			Value = _value,
		};
}