// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGetApplicationCommandsArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Applications;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGetApplicationCommandsArgsBuilder
{
	private bool? _withLocalizations;

	public DiscordGetApplicationCommandsArgsBuilder WithWithLocalizations(bool? withLocalizations)
	{
		_withLocalizations = withLocalizations;
		return this;
	}

	public DiscordGetApplicationCommandsArgs Build() =>
		new()
		{
			WithLocalizations = _withLocalizations,
		};
}