// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordApplicationCommandInteractionDataOptionBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Applications;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordApplicationCommandInteractionDataOptionBuilder
{
	private bool? _focused;
	private string _name = default!;
	private List<DiscordApplicationCommandInteractionDataOption>? _options;
	private DiscordApplicationCommandOptionType _type = default!;
	private object? _value;

	public DiscordApplicationCommandInteractionDataOptionBuilder WithFocused(bool? focused)
	{
		_focused = focused;
		return this;
	}

	public DiscordApplicationCommandInteractionDataOptionBuilder WithName(string name)
	{
		_name = name;
		return this;
	}

	public DiscordApplicationCommandInteractionDataOptionBuilder AddOption(Action<DiscordApplicationCommandInteractionDataOptionBuilder> builderAction)
	{
		var builder = new DiscordApplicationCommandInteractionDataOptionBuilder();
		builderAction(obj: builder);
		_options ??= new List<DiscordApplicationCommandInteractionDataOption>();
		_options.Add(item: builder.Build());
		return this;
	}

	public DiscordApplicationCommandInteractionDataOptionBuilder AddOption(DiscordApplicationCommandInteractionDataOption item)
	{
		_options ??= new List<DiscordApplicationCommandInteractionDataOption>();
		_options.Add(item: item);
		return this;
	}

	public DiscordApplicationCommandInteractionDataOptionBuilder WithType(DiscordApplicationCommandOptionType type)
	{
		_type = type;
		return this;
	}

	public DiscordApplicationCommandInteractionDataOptionBuilder WithValue(object? value)
	{
		_value = value;
		return this;
	}

	public DiscordApplicationCommandInteractionDataOption Build() =>
		new()
		{
			Focused = _focused,
			Name = _name,
			Options = _options?.ToImmutableArray(),
			Type = _type,
			Value = _value,
		};
}