// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordInstallParamsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Applications;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordInstallParamsBuilder
{
	private DiscordPermissions _permissions = default!;
	private readonly List<string> _scopes = new();

	public DiscordInstallParamsBuilder WithPermissions(DiscordPermissions permissions)
	{
		_permissions = permissions;
		return this;
	}

	public DiscordInstallParamsBuilder AddScope(string scope)
	{
		_scopes.Add(item: scope);
		return this;
	}

	public DiscordInstallParams Build() =>
		new()
		{
			Permissions = _permissions,
			Scopes = _scopes.ToImmutableArray(),
		};
}