// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildApplicationCommandPermissionsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Commands;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildApplicationCommandPermissionsBuilder
{
	private ulong _applicationId = default!;
	private ulong _guildId = default!;
	private ulong _id = default!;
	private readonly List<DiscordApplicationCommandPermissions> _permissions = new();

	public DiscordGuildApplicationCommandPermissionsBuilder WithApplicationId(ulong applicationId)
	{
		_applicationId = applicationId;
		return this;
	}

	public DiscordGuildApplicationCommandPermissionsBuilder WithGuildId(ulong guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordGuildApplicationCommandPermissionsBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public DiscordGuildApplicationCommandPermissionsBuilder AddPermission(Action<DiscordApplicationCommandPermissionsBuilder> builderAction)
	{
		var builder = new DiscordApplicationCommandPermissionsBuilder();
		builderAction(obj: builder);
		_permissions.Add(item: builder.Build());
		return this;
	}

	public DiscordGuildApplicationCommandPermissionsBuilder AddPermission(DiscordApplicationCommandPermissions item)
	{
		_permissions.Add(item: item);
		return this;
	}

	public DiscordGuildApplicationCommandPermissions Build() =>
		new()
		{
			ApplicationId = _applicationId,
			GuildId = _guildId,
			Id = _id,
			Permissions = _permissions.ToImmutableArray(),
		};
}