// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordActivityUpdateBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Commands;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordActivityUpdateBuilder
{
	private string _name = default!;
	private string? _state;
	private DiscordActivityType _type = default!;
	private string? _url;

	public DiscordActivityUpdateBuilder WithName(string name)
	{
		_name = name;
		return this;
	}

	public DiscordActivityUpdateBuilder WithState(string? state)
	{
		_state = state;
		return this;
	}

	public DiscordActivityUpdateBuilder WithType(DiscordActivityType type)
	{
		_type = type;
		return this;
	}

	public DiscordActivityUpdateBuilder WithUrl(string? url)
	{
		_url = url;
		return this;
	}

	public DiscordActivityUpdate Build() =>
		new()
		{
			Name = _name,
			State = _state,
			Type = _type,
			Url = _url,
		};
}