// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordApplicationCommandPermissionsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Commands;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordApplicationCommandPermissionsBuilder
{
	private ulong _id = default!;
	private bool _permission = default!;
	private DiscordApplicationCommandPermissionType _type = default!;

	public DiscordApplicationCommandPermissionsBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public DiscordApplicationCommandPermissionsBuilder WithPermission(bool permission)
	{
		_permission = permission;
		return this;
	}

	public DiscordApplicationCommandPermissionsBuilder WithType(DiscordApplicationCommandPermissionType type)
	{
		_type = type;
		return this;
	}

	public DiscordApplicationCommandPermissions Build() =>
		new()
		{
			Id = _id,
			Permission = _permission,
			Type = _type,
		};
}