// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGatewayBotBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGatewayBotBuilder
{
	private DiscordSessionStartLimit _sessionStartLimit = default!;
	private int _shards = default!;
	private string _url = default!;

	public DiscordGatewayBotBuilder WithSessionStartLimit(DiscordSessionStartLimit sessionStartLimit)
	{
		_sessionStartLimit = sessionStartLimit;
		return this;
	}

	public DiscordGatewayBotBuilder WithShards(int shards)
	{
		_shards = shards;
		return this;
	}

	public DiscordGatewayBotBuilder WithUrl(string url)
	{
		_url = url;
		return this;
	}

	public DiscordGatewayBot Build() =>
		new()
		{
			SessionStartLimit = _sessionStartLimit,
			Shards = _shards,
			Url = _url,
		};
}