// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordSessionStartLimitBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordSessionStartLimitBuilder
{
	private int _maxConcurrency = default!;
	private int _remaining = default!;
	private int _resetAfter = default!;
	private int _total = default!;

	public DiscordSessionStartLimitBuilder WithMaxConcurrency(int maxConcurrency)
	{
		_maxConcurrency = maxConcurrency;
		return this;
	}

	public DiscordSessionStartLimitBuilder WithRemaining(int remaining)
	{
		_remaining = remaining;
		return this;
	}

	public DiscordSessionStartLimitBuilder WithResetAfter(int resetAfter)
	{
		_resetAfter = resetAfter;
		return this;
	}

	public DiscordSessionStartLimitBuilder WithTotal(int total)
	{
		_total = total;
		return this;
	}

	public DiscordSessionStartLimit Build() =>
		new()
		{
			MaxConcurrency = _maxConcurrency,
			Remaining = _remaining,
			ResetAfter = _resetAfter,
			Total = _total,
		};
}