// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGatewayBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGatewayBuilder
{
	private string _url = default!;

	public DiscordGatewayBuilder WithUrl(string url)
	{
		_url = url;
		return this;
	}

	public DiscordGateway Build() =>
		new()
		{
			Url = _url,
		};
}