// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordRateLimitResponseBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Rest;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordRateLimitResponseBuilder
{
	private bool _global = default!;
	private string _message = default!;
	private TimeSpan _retryAfter = default!;

	public DiscordRateLimitResponseBuilder WithGlobal(bool global)
	{
		_global = global;
		return this;
	}

	public DiscordRateLimitResponseBuilder WithMessage(string message)
	{
		_message = message;
		return this;
	}

	public DiscordRateLimitResponseBuilder WithRetryAfter(TimeSpan retryAfter)
	{
		_retryAfter = retryAfter;
		return this;
	}

	public DiscordRateLimitResponse Build() =>
		new()
		{
			Global = _global,
			Message = _message,
			RetryAfter = _retryAfter,
		};
}