// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordErrorResponseBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Rest;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordErrorResponseBuilder
{
	private DiscordJsonErrorCode _code = default!;
	private string? _jsonKey;
	private string _message = default!;

	public DiscordErrorResponseBuilder WithCode(DiscordJsonErrorCode code)
	{
		_code = code;
		return this;
	}

	public DiscordErrorResponseBuilder WithJsonKey(string? jsonKey)
	{
		_jsonKey = jsonKey;
		return this;
	}

	public DiscordErrorResponseBuilder WithMessage(string message)
	{
		_message = message;
		return this;
	}

	public DiscordErrorResponse Build() =>
		new()
		{
			Code = _code,
			JsonKey = _jsonKey,
			Message = _message,
		};
}