// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordBucketResponseBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Rest;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordBucketResponseBuilder
{
	private string _bucket = default!;
	private double _discordReset = default!;
	private int _limit = default!;
	private int _remaining = default!;
	private TimeSpan _resetAfter = default!;

	public DiscordBucketResponseBuilder WithBucket(string bucket)
	{
		_bucket = bucket;
		return this;
	}

	public DiscordBucketResponseBuilder WithDiscordReset(double discordReset)
	{
		_discordReset = discordReset;
		return this;
	}

	public DiscordBucketResponseBuilder WithLimit(int limit)
	{
		_limit = limit;
		return this;
	}

	public DiscordBucketResponseBuilder WithRemaining(int remaining)
	{
		_remaining = remaining;
		return this;
	}

	public DiscordBucketResponseBuilder WithResetAfter(TimeSpan resetAfter)
	{
		_resetAfter = resetAfter;
		return this;
	}

	public DiscordBucketResponse Build() =>
		new()
		{
			Bucket = _bucket,
			DiscordReset = _discordReset,
			Limit = _limit,
			Remaining = _remaining,
			ResetAfter = _resetAfter,
		};
}