// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordBulkDeleteMessagesArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels.Messages;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordBulkDeleteMessagesArgsBuilder
{
	private readonly List<ulong> _messages = new();

	public DiscordBulkDeleteMessagesArgsBuilder AddMessage(ulong message)
	{
		_messages.Add(item: message);
		return this;
	}

	public DiscordBulkDeleteMessagesArgs Build() =>
		new()
		{
			Messages = _messages.ToImmutableArray(),
		};
}