// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordReactionBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels.Messages;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordReactionBuilder
{
	private int _count = default!;
	private DiscordEmoji _emoji = default!;
	private bool _me = default!;

	public DiscordReactionBuilder WithCount(int count)
	{
		_count = count;
		return this;
	}

	public DiscordReactionBuilder WithEmoji(DiscordEmoji emoji)
	{
		_emoji = emoji;
		return this;
	}

	public DiscordReactionBuilder WithMe(bool me)
	{
		_me = me;
		return this;
	}

	public DiscordReaction Build() =>
		new()
		{
			Count = _count,
			Emoji = _emoji,
			Me = _me,
		};
}