// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordCreateDmArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels.Messages;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordCreateDmArgsBuilder
{
	private ulong _recipientId = default!;

	public DiscordCreateDmArgsBuilder WithRecipientId(ulong recipientId)
	{
		_recipientId = recipientId;
		return this;
	}

	public DiscordCreateDmArgs Build() =>
		new()
		{
			RecipientId = _recipientId,
		};
}