// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordVideoBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels.Messages.Embeds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordVideoBuilder
{
	private string? _url;

	public DiscordVideoBuilder WithUrl(string? url)
	{
		_url = url;
		return this;
	}

	public DiscordVideo Build() =>
		new()
		{
			Url = _url,
		};
}