// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordFooterBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels.Messages.Embeds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordFooterBuilder
{
	private string? _iconUrl;
	private string _text = default!;

	public DiscordFooterBuilder WithIconUrl(string? iconUrl)
	{
		_iconUrl = iconUrl;
		return this;
	}

	public DiscordFooterBuilder WithText(string text)
	{
		_text = text;
		return this;
	}

	public DiscordFooter Build() =>
		new()
		{
			IconUrl = _iconUrl,
			Text = _text,
		};
}