// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordAuthorBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels.Messages.Embeds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordAuthorBuilder
{
	private string? _iconUrl;
	private string _name = default!;
	private string? _url;

	public DiscordAuthorBuilder WithIconUrl(string? iconUrl)
	{
		_iconUrl = iconUrl;
		return this;
	}

	public DiscordAuthorBuilder WithName(string name)
	{
		_name = name;
		return this;
	}

	public DiscordAuthorBuilder WithUrl(string? url)
	{
		_url = url;
		return this;
	}

	public DiscordAuthor Build() =>
		new()
		{
			IconUrl = _iconUrl,
			Name = _name,
			Url = _url,
		};
}