// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordImageBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels.Messages.Embeds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordImageBuilder
{
	private string _url = default!;

	public DiscordImageBuilder WithUrl(string url)
	{
		_url = url;
		return this;
	}

	public DiscordImage Build() =>
		new()
		{
			Url = _url,
		};
}