// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordInteractionResponseArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Interactions;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordInteractionResponseArgsBuilder
{
	private DiscordInteractionCallbackData? _data;
	private DiscordInteractionCallbackType _type = default!;

	public DiscordInteractionResponseArgsBuilder WithData(DiscordInteractionCallbackData? data)
	{
		_data = data;
		return this;
	}

	public DiscordInteractionResponseArgsBuilder WithType(DiscordInteractionCallbackType type)
	{
		_type = type;
		return this;
	}

	public DiscordInteractionResponseArgs Build() =>
		new()
		{
			Data = _data,
			Type = _type,
		};
}