// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordInteractionCallbackAutocompleteBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Interactions;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordInteractionCallbackAutocompleteBuilder
{
	private readonly List<DiscordApplicationCommandOptionChoice> _choices = new();

	public DiscordInteractionCallbackAutocompleteBuilder AddChoice(Action<DiscordApplicationCommandOptionChoiceBuilder> builderAction)
	{
		var builder = new DiscordApplicationCommandOptionChoiceBuilder();
		builderAction(obj: builder);
		_choices.Add(item: builder.Build());
		return this;
	}

	public DiscordInteractionCallbackAutocompleteBuilder AddChoice(DiscordApplicationCommandOptionChoice item)
	{
		_choices.Add(item: item);
		return this;
	}

	public DiscordInteractionCallbackAutocomplete Build() =>
		new()
		{
			Choices = _choices.ToImmutableArray(),
		};
}