// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordInteractionCallbackModalBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Interactions;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordInteractionCallbackModalBuilder
{
	private readonly List<DiscordMessageComponent> _components = new();
	private string _customId = default!;
	private string _title = default!;

	public DiscordInteractionCallbackModalBuilder AddActionRow(Action<DiscordMessageActionRowBuilder> builderAction)
	{
		var builder = new DiscordMessageActionRowBuilder();
		builderAction(obj: builder);
		_components.Add(item: builder.Build());
		return this;
	}

	public DiscordInteractionCallbackModalBuilder WithCustomId(string customId)
	{
		_customId = customId;
		return this;
	}

	public DiscordInteractionCallbackModalBuilder WithTitle(string title)
	{
		_title = title;
		return this;
	}

	public DiscordInteractionCallbackModal Build() =>
		new()
		{
			Components = _components.ToImmutableArray(),
			CustomId = _customId,
			Title = _title,
		};
}