// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordInteractionDataBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Interactions;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordInteractionDataBuilder
{
	private List<DiscordMessageComponent>? _components;
	private DiscordMessageComponentType? _componentType;
	private string? _customId;
	private ulong? _id;
	private string? _name;
	private List<DiscordApplicationCommandInteractionDataOption>? _options;
	private DiscordApplicationCommandType? _type;
	private List<string>? _values;

	public DiscordInteractionDataBuilder AddActionRow(Action<DiscordMessageActionRowBuilder> builderAction)
	{
		var builder = new DiscordMessageActionRowBuilder();
		builderAction(obj: builder);
		_components ??= new List<DiscordMessageComponent>();
		_components.Add(item: builder.Build());
		return this;
	}

	public DiscordInteractionDataBuilder WithComponentType(DiscordMessageComponentType? componentType)
	{
		_componentType = componentType;
		return this;
	}

	public DiscordInteractionDataBuilder WithCustomId(string? customId)
	{
		_customId = customId;
		return this;
	}

	public DiscordInteractionDataBuilder WithId(ulong? id)
	{
		_id = id;
		return this;
	}

	public DiscordInteractionDataBuilder WithName(string? name)
	{
		_name = name;
		return this;
	}

	public DiscordInteractionDataBuilder AddOption(Action<DiscordApplicationCommandInteractionDataOptionBuilder> builderAction)
	{
		var builder = new DiscordApplicationCommandInteractionDataOptionBuilder();
		builderAction(obj: builder);
		_options ??= new List<DiscordApplicationCommandInteractionDataOption>();
		_options.Add(item: builder.Build());
		return this;
	}

	public DiscordInteractionDataBuilder AddOption(DiscordApplicationCommandInteractionDataOption item)
	{
		_options ??= new List<DiscordApplicationCommandInteractionDataOption>();
		_options.Add(item: item);
		return this;
	}

	public DiscordInteractionDataBuilder WithType(DiscordApplicationCommandType? type)
	{
		_type = type;
		return this;
	}

	public DiscordInteractionDataBuilder AddValue(string value)
	{
		_values ??= new List<string>();
		_values.Add(item: value);
		return this;
	}

	public DiscordInteractionData Build() =>
		new()
		{
			Components = _components?.ToImmutableArray(),
			ComponentType = _componentType,
			CustomId = _customId,
			Id = _id,
			Name = _name,
			Options = _options?.ToImmutableArray(),
			Type = _type,
			Values = _values?.ToImmutableArray(),
		};
}