// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordInteractionBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Interactions;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordInteractionBuilder
{
	private ulong _applicationId = default!;
	private ulong? _channelId;
	private DiscordInteractionData? _data;
	private ulong? _guildId;
	private ulong _id = default!;
	private DiscordGuildMember? _member;
	private DiscordMessage? _message;
	private string _token = default!;
	private DiscordInteractionType _type = default!;
	private DiscordUser? _user;

	public DiscordInteractionBuilder WithApplicationId(ulong applicationId)
	{
		_applicationId = applicationId;
		return this;
	}

	public DiscordInteractionBuilder WithChannelId(ulong? channelId)
	{
		_channelId = channelId;
		return this;
	}

	public DiscordInteractionBuilder WithData(DiscordInteractionData? data)
	{
		_data = data;
		return this;
	}

	public DiscordInteractionBuilder WithGuildId(ulong? guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordInteractionBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public DiscordInteractionBuilder WithMember(DiscordGuildMember? member)
	{
		_member = member;
		return this;
	}

	public DiscordInteractionBuilder WithMessage(DiscordMessage? message)
	{
		_message = message;
		return this;
	}

	public DiscordInteractionBuilder WithToken(string token)
	{
		_token = token;
		return this;
	}

	public DiscordInteractionBuilder WithType(DiscordInteractionType type)
	{
		_type = type;
		return this;
	}

	public DiscordInteractionBuilder WithUser(DiscordUser? user)
	{
		_user = user;
		return this;
	}

	public DiscordInteraction Build() =>
		new()
		{
			ApplicationId = _applicationId,
			ChannelId = _channelId,
			Data = _data,
			GuildId = _guildId,
			Id = _id,
			Member = _member,
			Message = _message,
			Token = _token,
			Type = _type,
			User = _user,
		};
}