// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordUserBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Users;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordUserBuilder
{
	private string? _avatar;
	private bool? _bot;
	private string _discriminator = default!;
	private string? _globalName;
	private ulong _id = default!;
	private string _username = default!;

	public DiscordUserBuilder WithAvatar(string? avatar)
	{
		_avatar = avatar;
		return this;
	}

	public DiscordUserBuilder WithBot(bool? bot)
	{
		_bot = bot;
		return this;
	}

	public DiscordUserBuilder WithDiscriminator(string discriminator)
	{
		_discriminator = discriminator;
		return this;
	}

	public DiscordUserBuilder WithGlobalName(string? globalName)
	{
		_globalName = globalName;
		return this;
	}

	public DiscordUserBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public DiscordUserBuilder WithUsername(string username)
	{
		_username = username;
		return this;
	}

	public DiscordUser Build() =>
		new()
		{
			Avatar = _avatar,
			Bot = _bot,
			Discriminator = _discriminator,
			GlobalName = _globalName,
			Id = _id,
			Username = _username,
		};
}