// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordDefaultReactionBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordDefaultReactionBuilder
{
	private ulong? _emojiId;
	private string? _emojiName;

	public DiscordDefaultReactionBuilder WithEmojiId(ulong? emojiId)
	{
		_emojiId = emojiId;
		return this;
	}

	public DiscordDefaultReactionBuilder WithEmojiName(string? emojiName)
	{
		_emojiName = emojiName;
		return this;
	}

	public DiscordDefaultReaction Build() =>
		new()
		{
			EmojiId = _emojiId,
			EmojiName = _emojiName,
		};
}