// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordThreadResponseBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordThreadResponseBuilder
{
	private bool _hasMore = default!;
	private readonly List<DiscordChannel> _threads = new();

	public DiscordThreadResponseBuilder WithHasMore(bool hasMore)
	{
		_hasMore = hasMore;
		return this;
	}

	public DiscordThreadResponseBuilder AddThread(Action<DiscordChannelBuilder> builderAction)
	{
		var builder = new DiscordChannelBuilder();
		builderAction(obj: builder);
		_threads.Add(item: builder.Build());
		return this;
	}

	public DiscordThreadResponseBuilder AddThread(DiscordChannel item)
	{
		_threads.Add(item: item);
		return this;
	}

	public DiscordThreadResponse Build() =>
		new()
		{
			HasMore = _hasMore,
			Threads = _threads.ToImmutableArray(),
		};
}