// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordListPublicArchivedThreadsArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordListPublicArchivedThreadsArgsBuilder
{
	private DateTime? _before;
	private int? _limit;

	public DiscordListPublicArchivedThreadsArgsBuilder WithBefore(DateTime? before)
	{
		_before = before;
		return this;
	}

	public DiscordListPublicArchivedThreadsArgsBuilder WithLimit(int? limit)
	{
		_limit = limit;
		return this;
	}

	public DiscordListPublicArchivedThreadsArgs Build() =>
		new()
		{
			Before = _before,
			Limit = _limit,
		};
}