// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordThreadMetadataBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordThreadMetadataBuilder
{
	private bool _archived = default!;
	private DateTime _archiveTimestamp = default!;

	public DiscordThreadMetadataBuilder WithArchived(bool archived)
	{
		_archived = archived;
		return this;
	}

	public DiscordThreadMetadataBuilder WithArchiveTimestamp(DateTime archiveTimestamp)
	{
		_archiveTimestamp = archiveTimestamp;
		return this;
	}

	public DiscordThreadMetadata Build() =>
		new()
		{
			Archived = _archived,
			ArchiveTimestamp = _archiveTimestamp,
		};
}