// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordModifyThreadArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordModifyThreadArgsBuilder
{
	private bool? _archived;
	private DiscordChannelFlags? _flags;
	private string? _name;

	public DiscordModifyThreadArgsBuilder WithArchived(bool? archived)
	{
		_archived = archived;
		return this;
	}

	public DiscordModifyThreadArgsBuilder WithFlags(DiscordChannelFlags? flags)
	{
		_flags = flags;
		return this;
	}

	public DiscordModifyThreadArgsBuilder WithName(string? name)
	{
		_name = name;
		return this;
	}

	public DiscordModifyThreadArgs Build() =>
		new()
		{
			Archived = _archived,
			Flags = _flags,
			Name = _name,
		};
}