// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordActiveThreadResponseBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordActiveThreadResponseBuilder
{
	private readonly List<DiscordChannel> _threads = new();

	public DiscordActiveThreadResponseBuilder AddThread(Action<DiscordChannelBuilder> builderAction)
	{
		var builder = new DiscordChannelBuilder();
		builderAction(obj: builder);
		_threads.Add(item: builder.Build());
		return this;
	}

	public DiscordActiveThreadResponseBuilder AddThread(DiscordChannel item)
	{
		_threads.Add(item: item);
		return this;
	}

	public DiscordActiveThreadResponse Build() =>
		new()
		{
			Threads = _threads.ToImmutableArray(),
		};
}