// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordStartThreadWithMessageArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordStartThreadWithMessageArgsBuilder
{
	private int? _autoArchiveDuration;
	private string _name = default!;

	public DiscordStartThreadWithMessageArgsBuilder WithAutoArchiveDuration(int? autoArchiveDuration)
	{
		_autoArchiveDuration = autoArchiveDuration;
		return this;
	}

	public DiscordStartThreadWithMessageArgsBuilder WithName(string name)
	{
		_name = name;
		return this;
	}

	public DiscordStartThreadWithMessageArgs Build() =>
		new()
		{
			AutoArchiveDuration = _autoArchiveDuration,
			Name = _name,
		};
}