// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordChannelBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds.Channels;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordChannelBuilder
{
	private List<DiscordForumTag>? _availableTags;
	private int? _defaultAutoArchiveDuration;
	private DiscordForumLayoutType? _defaultForumLayout;
	private DiscordDefaultReaction? _defaultReactionEmoji;
	private DiscordSortOrderType? _defaultSortOrder;
	private ulong? _guildId;
	private ulong _id = default!;
	private string? _name;
	private ulong? _parentId;
	private List<DiscordPermissionOverwrite>? _permissionOverwrites;
	private int? _position;
	private DiscordThreadMetadata? _threadMetadata;
	private string? _topic;
	private DiscordChannelType _type = default!;

	public DiscordChannelBuilder AddAvailableTag(Action<DiscordForumTagBuilder> builderAction)
	{
		var builder = new DiscordForumTagBuilder();
		builderAction(obj: builder);
		_availableTags ??= new List<DiscordForumTag>();
		_availableTags.Add(item: builder.Build());
		return this;
	}

	public DiscordChannelBuilder AddAvailableTag(DiscordForumTag item)
	{
		_availableTags ??= new List<DiscordForumTag>();
		_availableTags.Add(item: item);
		return this;
	}

	public DiscordChannelBuilder WithDefaultAutoArchiveDuration(int? defaultAutoArchiveDuration)
	{
		_defaultAutoArchiveDuration = defaultAutoArchiveDuration;
		return this;
	}

	public DiscordChannelBuilder WithDefaultForumLayout(DiscordForumLayoutType? defaultForumLayout)
	{
		_defaultForumLayout = defaultForumLayout;
		return this;
	}

	public DiscordChannelBuilder WithDefaultReactionEmoji(DiscordDefaultReaction? defaultReactionEmoji)
	{
		_defaultReactionEmoji = defaultReactionEmoji;
		return this;
	}

	public DiscordChannelBuilder WithDefaultSortOrder(DiscordSortOrderType? defaultSortOrder)
	{
		_defaultSortOrder = defaultSortOrder;
		return this;
	}

	public DiscordChannelBuilder WithGuildId(ulong? guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordChannelBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public DiscordChannelBuilder WithName(string? name)
	{
		_name = name;
		return this;
	}

	public DiscordChannelBuilder WithParentId(ulong? parentId)
	{
		_parentId = parentId;
		return this;
	}

	public DiscordChannelBuilder AddPermissionOverwrite(Action<DiscordPermissionOverwriteBuilder> builderAction)
	{
		var builder = new DiscordPermissionOverwriteBuilder();
		builderAction(obj: builder);
		_permissionOverwrites ??= new List<DiscordPermissionOverwrite>();
		_permissionOverwrites.Add(item: builder.Build());
		return this;
	}

	public DiscordChannelBuilder AddPermissionOverwrite(DiscordPermissionOverwrite item)
	{
		_permissionOverwrites ??= new List<DiscordPermissionOverwrite>();
		_permissionOverwrites.Add(item: item);
		return this;
	}

	public DiscordChannelBuilder WithPosition(int? position)
	{
		_position = position;
		return this;
	}

	public DiscordChannelBuilder WithThreadMetadata(DiscordThreadMetadata? threadMetadata)
	{
		_threadMetadata = threadMetadata;
		return this;
	}

	public DiscordChannelBuilder WithTopic(string? topic)
	{
		_topic = topic;
		return this;
	}

	public DiscordChannelBuilder WithType(DiscordChannelType type)
	{
		_type = type;
		return this;
	}

	public DiscordChannel Build() =>
		new()
		{
			AvailableTags = _availableTags?.ToImmutableArray(),
			DefaultAutoArchiveDuration = _defaultAutoArchiveDuration,
			DefaultForumLayout = _defaultForumLayout,
			DefaultReactionEmoji = _defaultReactionEmoji,
			DefaultSortOrder = _defaultSortOrder,
			GuildId = _guildId,
			Id = _id,
			Name = _name,
			ParentId = _parentId,
			PermissionOverwrites = _permissionOverwrites?.ToImmutableArray(),
			Position = _position,
			ThreadMetadata = _threadMetadata,
			Topic = _topic,
			Type = _type,
		};
}