// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordListGuildMembersArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordListGuildMembersArgsBuilder
{
	private ulong? _after;
	private int? _limit;

	public DiscordListGuildMembersArgsBuilder WithAfter(ulong? after)
	{
		_after = after;
		return this;
	}

	public DiscordListGuildMembersArgsBuilder WithLimit(int? limit)
	{
		_limit = limit;
		return this;
	}

	public DiscordListGuildMembersArgs Build() =>
		new()
		{
			After = _after,
			Limit = _limit,
		};
}