// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordCreateGuildEmojiArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordCreateGuildEmojiArgsBuilder
{
	private string _filePath = default!;
	private string _name = default!;

	public DiscordCreateGuildEmojiArgsBuilder WithFilePath(string filePath)
	{
		_filePath = filePath;
		return this;
	}

	public DiscordCreateGuildEmojiArgsBuilder WithName(string name)
	{
		_name = name;
		return this;
	}

	public DiscordCreateGuildEmojiArgs Build() =>
		new()
		{
			FilePath = _filePath,
			Name = _name,
		};
}