// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGetGuildArgsBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGetGuildArgsBuilder
{
	private bool? _withCounts;

	public DiscordGetGuildArgsBuilder WithWithCounts(bool? withCounts)
	{
		_withCounts = withCounts;
		return this;
	}

	public DiscordGetGuildArgs Build() =>
		new()
		{
			WithCounts = _withCounts,
		};
}