// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildMemberBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildMemberBuilder
{
	private string? _nick;
	private DiscordPermissions? _permissions;
	private readonly List<ulong> _roles = new();
	private DiscordUser? _user;

	public DiscordGuildMemberBuilder WithNick(string? nick)
	{
		_nick = nick;
		return this;
	}

	public DiscordGuildMemberBuilder WithPermissions(DiscordPermissions? permissions)
	{
		_permissions = permissions;
		return this;
	}

	public DiscordGuildMemberBuilder AddRole(ulong role)
	{
		_roles.Add(item: role);
		return this;
	}

	public DiscordGuildMemberBuilder WithUser(DiscordUser? user)
	{
		_user = user;
		return this;
	}

	public DiscordGuildMember Build() =>
		new()
		{
			Nick = _nick,
			Permissions = _permissions,
			Roles = _roles.ToImmutableArray(),
			User = _user,
		};
}