// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordPermissionOverwriteBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Guilds;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordPermissionOverwriteBuilder
{
	private DiscordPermissions _allow = default!;
	private DiscordPermissions _deny = default!;
	private ulong _id = default!;
	private DiscordPermissionOverwriteType _type = default!;

	public DiscordPermissionOverwriteBuilder WithAllow(DiscordPermissions allow)
	{
		_allow = allow;
		return this;
	}

	public DiscordPermissionOverwriteBuilder WithDeny(DiscordPermissions deny)
	{
		_deny = deny;
		return this;
	}

	public DiscordPermissionOverwriteBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public DiscordPermissionOverwriteBuilder WithType(DiscordPermissionOverwriteType type)
	{
		_type = type;
		return this;
	}

	public DiscordPermissionOverwrite Build() =>
		new()
		{
			Allow = _allow,
			Deny = _deny,
			Id = _id,
			Type = _type,
		};
}