// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildMemberAddBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildMemberAddBuilder
{
	private ulong _guildId = default!;
	private string? _nick;
	private DiscordPermissions? _permissions;
	private readonly List<ulong> _roles = new();
	private DiscordUser? _user;

	public DiscordGuildMemberAddBuilder WithGuildId(ulong guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordGuildMemberAddBuilder WithNick(string? nick)
	{
		_nick = nick;
		return this;
	}

	public DiscordGuildMemberAddBuilder WithPermissions(DiscordPermissions? permissions)
	{
		_permissions = permissions;
		return this;
	}

	public DiscordGuildMemberAddBuilder AddRole(ulong role)
	{
		_roles.Add(item: role);
		return this;
	}

	public DiscordGuildMemberAddBuilder WithUser(DiscordUser? user)
	{
		_user = user;
		return this;
	}

	public DiscordGuildMemberAdd Build() =>
		new()
		{
			GuildId = _guildId,
			Nick = _nick,
			Permissions = _permissions,
			Roles = _roles.ToImmutableArray(),
			User = _user,
		};
}