// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordMessageReactionRemoveBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordMessageReactionRemoveBuilder
{
	private ulong _channelId = default!;
	private DiscordEmoji _emoji = default!;
	private ulong? _guildId;
	private ulong _messageId = default!;
	private ulong _userId = default!;

	public DiscordMessageReactionRemoveBuilder WithChannelId(ulong channelId)
	{
		_channelId = channelId;
		return this;
	}

	public DiscordMessageReactionRemoveBuilder WithEmoji(DiscordEmoji emoji)
	{
		_emoji = emoji;
		return this;
	}

	public DiscordMessageReactionRemoveBuilder WithGuildId(ulong? guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordMessageReactionRemoveBuilder WithMessageId(ulong messageId)
	{
		_messageId = messageId;
		return this;
	}

	public DiscordMessageReactionRemoveBuilder WithUserId(ulong userId)
	{
		_userId = userId;
		return this;
	}

	public DiscordMessageReactionRemove Build() =>
		new()
		{
			ChannelId = _channelId,
			Emoji = _emoji,
			GuildId = _guildId,
			MessageId = _messageId,
			UserId = _userId,
		};
}