// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildRoleCreateBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildRoleCreateBuilder
{
	private ulong _guildId = default!;
	private DiscordRole _role = default!;

	public DiscordGuildRoleCreateBuilder WithGuildId(ulong guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordGuildRoleCreateBuilder WithRole(DiscordRole role)
	{
		_role = role;
		return this;
	}

	public DiscordGuildRoleCreate Build() =>
		new()
		{
			GuildId = _guildId,
			Role = _role,
		};
}