// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildMemberUpdateBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildMemberUpdateBuilder
{
	private ulong _guildId = default!;
	private string? _nick;
	private readonly List<ulong> _roles = new();
	private DiscordUser _user = default!;

	public DiscordGuildMemberUpdateBuilder WithGuildId(ulong guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordGuildMemberUpdateBuilder WithNick(string? nick)
	{
		_nick = nick;
		return this;
	}

	public DiscordGuildMemberUpdateBuilder AddRole(ulong role)
	{
		_roles.Add(item: role);
		return this;
	}

	public DiscordGuildMemberUpdateBuilder WithUser(DiscordUser user)
	{
		_user = user;
		return this;
	}

	public DiscordGuildMemberUpdate Build() =>
		new()
		{
			GuildId = _guildId,
			Nick = _nick,
			Roles = _roles.ToImmutableArray(),
			User = _user,
		};
}