// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordMessageReactionAddBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordMessageReactionAddBuilder
{
	private ulong _channelId = default!;
	private DiscordEmoji _emoji = default!;
	private ulong? _guildId;
	private DiscordGuildMember? _member;
	private ulong? _messageAuthorId;
	private ulong _messageId = default!;
	private ulong _userId = default!;

	public DiscordMessageReactionAddBuilder WithChannelId(ulong channelId)
	{
		_channelId = channelId;
		return this;
	}

	public DiscordMessageReactionAddBuilder WithEmoji(DiscordEmoji emoji)
	{
		_emoji = emoji;
		return this;
	}

	public DiscordMessageReactionAddBuilder WithGuildId(ulong? guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordMessageReactionAddBuilder WithMember(DiscordGuildMember? member)
	{
		_member = member;
		return this;
	}

	public DiscordMessageReactionAddBuilder WithMessageAuthorId(ulong? messageAuthorId)
	{
		_messageAuthorId = messageAuthorId;
		return this;
	}

	public DiscordMessageReactionAddBuilder WithMessageId(ulong messageId)
	{
		_messageId = messageId;
		return this;
	}

	public DiscordMessageReactionAddBuilder WithUserId(ulong userId)
	{
		_userId = userId;
		return this;
	}

	public DiscordMessageReactionAdd Build() =>
		new()
		{
			ChannelId = _channelId,
			Emoji = _emoji,
			GuildId = _guildId,
			Member = _member,
			MessageAuthorId = _messageAuthorId,
			MessageId = _messageId,
			UserId = _userId,
		};
}