// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordReadyBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordReadyBuilder
{
	private DiscordApplication _application = default!;
	private readonly List<UnavailableGuild> _guilds = new();
	private string _resumeGatewayUrl = default!;
	private string _sessionId = default!;
	private DiscordShard? _shard;
	private DiscordUser _user = default!;
	private int _v = default!;

	public DiscordReadyBuilder WithApplication(DiscordApplication application)
	{
		_application = application;
		return this;
	}

	public DiscordReadyBuilder AddGuild(Action<UnavailableGuildBuilder> builderAction)
	{
		var builder = new UnavailableGuildBuilder();
		builderAction(obj: builder);
		_guilds.Add(item: builder.Build());
		return this;
	}

	public DiscordReadyBuilder AddGuild(UnavailableGuild item)
	{
		_guilds.Add(item: item);
		return this;
	}

	public DiscordReadyBuilder WithResumeGatewayUrl(string resumeGatewayUrl)
	{
		_resumeGatewayUrl = resumeGatewayUrl;
		return this;
	}

	public DiscordReadyBuilder WithSessionId(string sessionId)
	{
		_sessionId = sessionId;
		return this;
	}

	public DiscordReadyBuilder WithShard(DiscordShard? shard)
	{
		_shard = shard;
		return this;
	}

	public DiscordReadyBuilder WithUser(DiscordUser user)
	{
		_user = user;
		return this;
	}

	public DiscordReadyBuilder WithV(int v)
	{
		_v = v;
		return this;
	}

	public DiscordReady Build() =>
		new()
		{
			Application = _application,
			Guilds = _guilds.ToImmutableArray(),
			ResumeGatewayUrl = _resumeGatewayUrl,
			SessionId = _sessionId,
			Shard = _shard,
			User = _user,
			V = _v,
		};
}