// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildMemberRemoveBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildMemberRemoveBuilder
{
	private ulong _guildId = default!;
	private DiscordUser _user = default!;

	public DiscordGuildMemberRemoveBuilder WithGuildId(ulong guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordGuildMemberRemoveBuilder WithUser(DiscordUser user)
	{
		_user = user;
		return this;
	}

	public DiscordGuildMemberRemove Build() =>
		new()
		{
			GuildId = _guildId,
			User = _user,
		};
}