// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordMessageDeleteBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordMessageDeleteBuilder
{
	private ulong _channelId = default!;
	private ulong? _guildId;
	private ulong _id = default!;

	public DiscordMessageDeleteBuilder WithChannelId(ulong channelId)
	{
		_channelId = channelId;
		return this;
	}

	public DiscordMessageDeleteBuilder WithGuildId(ulong? guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordMessageDeleteBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public DiscordMessageDelete Build() =>
		new()
		{
			ChannelId = _channelId,
			GuildId = _guildId,
			Id = _id,
		};
}