// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildRoleDeleteBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildRoleDeleteBuilder
{
	private ulong _guildId = default!;
	private ulong _roleId = default!;

	public DiscordGuildRoleDeleteBuilder WithGuildId(ulong guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordGuildRoleDeleteBuilder WithRoleId(ulong roleId)
	{
		_roleId = roleId;
		return this;
	}

	public DiscordGuildRoleDelete Build() =>
		new()
		{
			GuildId = _guildId,
			RoleId = _roleId,
		};
}