// -------------------------------------------------------------------------------------------------
// <copyright file="DiscordGuildRoleUpdateBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class DiscordGuildRoleUpdateBuilder
{
	private ulong _guildId = default!;
	private DiscordRole _role = default!;

	public DiscordGuildRoleUpdateBuilder WithGuildId(ulong guildId)
	{
		_guildId = guildId;
		return this;
	}

	public DiscordGuildRoleUpdateBuilder WithRole(DiscordRole role)
	{
		_role = role;
		return this;
	}

	public DiscordGuildRoleUpdate Build() =>
		new()
		{
			GuildId = _guildId,
			Role = _role,
		};
}