// -------------------------------------------------------------------------------------------------
// <copyright file="UnavailableGuildBuilder.cs" company="kpop.fan">
//   Copyright (c) 2025 kpop.fan. All rights reserved.
// </copyright>
// -------------------------------------------------------------------------------------------------

namespace DiscordBotApi.Builders.Gateway.Events;

// WARNING! This file was generated by a tool.
//          Any changes made to this file will be lost if the code is regenerated.
public class UnavailableGuildBuilder
{
	private ulong _id = default!;
	private bool? _unavailable;

	public UnavailableGuildBuilder WithId(ulong id)
	{
		_id = id;
		return this;
	}

	public UnavailableGuildBuilder WithUnavailable(bool? unavailable)
	{
		_unavailable = unavailable;
		return this;
	}

	public UnavailableGuild Build() =>
		new()
		{
			Id = _id,
			Unavailable = _unavailable,
		};
}